"use client";
import Link from "next/link";
import { useState } from "react";

const initialProducts = [
  ["Noir Intense", "Amaderada", "$54.990", 18, "Activo"], ["Rose Élixir", "Floral", "$49.990", 7, "Activo"], ["Santal 09", "Amaderada", "$57.990", 4, "Stock bajo"], ["Citrus Breeze", "Cítrica", "$44.990", 23, "Activo"], ["Velvet Oud", "Oriental", "$59.990", 0, "Agotado"],
];
const orders = [["#AS-1048","Camila Soto","$109.980","Pagado"],["#AS-1047","Martín Vera","$49.990","Preparando"],["#AS-1046","Daniela Rojas","$57.990","Enviado"],["#AS-1045","Javiera Díaz","$94.980","Entregado"]];

export default function Admin(){
 const [section,setSection]=useState("Resumen"); const [products,setProducts]=useState(initialProducts); const [modal,setModal]=useState(false);
 return <main className="admin-shell"><aside className="admin-side"><Link href="/" className="brand"><span>AS</span><small>AROMA STUDIO</small></Link><p>ADMINISTRACIÓN</p><nav>{["Resumen","Productos","Pedidos","Clientes","Descuentos"].map((x,i)=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}><i>{["⌂","◇","▤","♙","%"] [i]}</i>{x}</button>)}</nav><div className="admin-side__bottom"><Link href="/">← Ver tienda</Link><button>⚙ Configuración</button></div></aside>
 <section className="admin-main"><header><div><p>JUEVES, 6 DE AGOSTO</p><h1>{section}</h1></div><div className="admin-user"><span>JS</span><div><strong>Jorge Silva</strong><small>Administrador</small></div></div></header>
 {section==="Resumen"&&<><div className="admin-welcome"><div><p>BUENAS TARDES</p><h2>Así va Aroma Studio hoy.</h2></div><button onClick={()=>setModal(true)}>+ NUEVO PRODUCTO</button></div><div className="stats"><article><p>VENTAS DEL MES <span>↗</span></p><strong>$2.486.740</strong><small>+18,4% vs. mes anterior</small></article><article><p>PEDIDOS <span>↗</span></p><strong>48</strong><small>+9 esta semana</small></article><article><p>TICKET PROMEDIO</p><strong>$51.807</strong><small>+4,2% vs. mes anterior</small></article><article><p>STOCK BAJO <span className="warn">!</span></p><strong>3</strong><small>Requieren atención</small></article></div><div className="admin-grid"><article className="chart-card"><div className="card-title"><div><p>RENDIMIENTO</p><h3>Ventas</h3></div><select><option>Últimos 7 días</option></select></div><div className="chart"><div className="chart-bars">{[42,58,36,72,61,88,78].map((h,i)=><span key={i} style={{height:`${h}%`}}><i>{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"][i]}</i></span>)}</div></div></article><article className="recent"><div className="card-title"><div><p>ACTIVIDAD</p><h3>Últimos pedidos</h3></div><button onClick={()=>setSection("Pedidos")}>VER TODOS →</button></div>{orders.slice(0,4).map(o=><div className="mini-order" key={o[0]}><span>{o[1].split(" ").map(x=>x[0]).join("")}</span><div><strong>{o[1]}</strong><small>{o[0]} · Hace 2 h</small></div><b>{o[2]}</b></div>)}</article></div></>}
 {section==="Productos"&&<AdminTable title="Catálogo de productos" action={()=>setModal(true)} headers={["Producto","Familia","Precio","Stock","Estado"]} rows={products}/>} 
 {section==="Pedidos"&&<AdminTable title="Pedidos recientes" headers={["Pedido","Cliente","Total","Estado"]} rows={orders}/>} 
 {!["Resumen","Productos","Pedidos"].includes(section)&&<div className="placeholder"><span>AS</span><h2>{section}</h2><p>Esta sección está preparada para integrar tus datos comerciales.</p></div>}
 </section>
 {modal&&<div className="admin-modal-bg"><form className="admin-modal" onSubmit={e=>{e.preventDefault();setProducts(p=>[["Nueva Fragancia","Unisex","$49.990",12,"Activo"],...p]);setModal(false)}}><div><h2>Nuevo producto</h2><button type="button" onClick={()=>setModal(false)}>×</button></div><label>Nombre<input required placeholder="Ej. Ámbar N° 04"/></label><label>Familia olfativa<select><option>Amaderada</option><option>Floral</option><option>Cítrica</option><option>Oriental</option></select></label><div className="form-row"><label>Precio<input type="number" placeholder="49990"/></label><label>Stock<input type="number" placeholder="12"/></label></div><button>CREAR PRODUCTO →</button></form></div>}
 </main>
}

function AdminTable({title,headers,rows,action}:{title:string;headers:string[];rows:(string|number)[][];action?:()=>void}){return <article className="admin-table-card"><div className="table-heading"><div><p>GESTIÓN</p><h2>{title}</h2></div>{action&&<button onClick={action}>+ NUEVO PRODUCTO</button>}</div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0&&title.includes("producto")?<><span className="table-bottle">AS</span><strong>{c}</strong></>:j===headers.length-1?<em className={`status status--${String(c).toLowerCase().replace(" ","")}`}>{c}</em>:c}</td>)}</tr>)}</tbody></table></div></article>}
